ambiente/urls.py
from django.conf.urls import url
from . import views

app_name = "ambiente"

urlpatterns = [
    url(r'^novo/$', views.novo_ambiente, name='novo'),
    url(r'^delete_event/$', views.deletar_evento, name='deletar_evento'),

    url(r'^(?P<pk>[0-9]+)/$', views.detalhe_ambiente, name='ambiente'),

    url(r'^(?P<pkambiente>[0-9]+)/proximos/$', views.proximos_eventos, name='proximos_eventos'),
    url(r'^(?P<pkambiente>[0-9]+)/proximos/(?P<username>[\w.@+-]+)/$', views.proximos_eventos_por_participante, name='proximos_eventos_por_participante'),

    url(r'^(?P<pkambiente>[0-9]+)/passados/$', views.eventos_passados, name='eventos_passados'),
    url(r'^(?P<pkambiente>[0-9]+)/passados/(?P<username>[\w.@+-]+)/$', views.eventos_passados_por_participante, name='eventos_passados_por_participante'),

    url(r'^(?P<pkambiente>[0-9]+)/multas/$', views.eventos_multados, name='eventos_multados'),
    # url(r'^(?P<pkambiente>[0-9]+)/passados/(?P<username>[\w.@+-]+)/$', views.eventos_passados_por_participante, name='eventos_passados_por_participante'),

    url(r'^(?P<pk>[0-9]+)/participantes/$', views.participantes, name='participantes'),
    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^remove_user/$', views.remove_user, name='remove_user'),

    url(r'^(?P<pk>[0-9]+)/eventos/$', views.eventos, name='eventos'),
    url(r'^(?P<pk>[0-9]+)/eventos/novo/$', views.new_evento, name='novoevento'),
    url(r'^(?P<pk>[0-9]+)/eventos/editar/(?P<pkevento>[0-9]+)$', views.editar_evento, name='editar_evento'),
    url(r'^(?P<pk>[0-9]+)/eventos/(?P<pkevento>[0-9]+)/$', views.evento, name='evento'),

    url(r'^(?P<pk>[0-9]+)/tarefa/(?P<pktarefa>[0-9]+)/$', views.tarefa, name='tarefa'),
    url(r'^(?P<pkambiente>[0-9]+)/tarefa/(?P<pktarefa>[0-9]+)/validar$', views.solicitacao_validacao, name='solicitacao_validacao'),
    url(r'^(?P<pkambiente>[0-9]+)/tarefa/(?P<pktarefa>[0-9]+)/refutar$', views.refutacao_validacao, name='refutacao_validacao'),
]

core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_page, name='login'),
	url(r'^autentica/$', views.entrar),
	url(r'^registra/$', views.register),
	url(r'^logout/$', views.make_logout),
	url(r'^minhaconta/$', views.settings, name='settings'),
	url(r'^excluiUser/$', views.excluiUser),
]

penalty/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles import views
import django

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ambiente/', include('ambiente.urls')),
    url(r'^', include('core.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ambiente/forms.py
from django import forms
from .models import Ambiente, Evento, ComentariosDeEventos
from django.contrib.admin.widgets import AdminDateWidget
from datetime import date
from bootstrap3_datetime.widgets import DateTimePicker

class AmbienteForm(forms.ModelForm):
	nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Informe o nome do ambiente'}),)
	descricao = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Considerações sobre o ambiente'}),)
	endereco = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Informe o endereço do ambiente'}),)
	
	class Meta:
		model = Ambiente
		fields = ('nome', 'descricao', 'endereco')

class EventoForm(forms.ModelForm):
	choice = None
	nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Informe o nome do evento'}),)
	descricao = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Considerações sobre o evento'}),)
	valor_multa = forms.FloatField(required=True, min_value=0, widget=forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Valor da multa em R$', 'id': 'form_homework', 'step': '0.1'}))
	quantidade_intervalos_repeticao = forms.IntegerField(min_value=1, required=True, widget=forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Determine um intervalo'}),)
	data_inicio = forms.DateField(widget=DateTimePicker(options={"format": "DD/MM/YYYY", "pickTime": False}), initial=date.today)
	data_fim = forms.DateField(widget=DateTimePicker(options={"format": "DD/MM/YYYY", "pickTime": False}), initial=date.fromordinal(date.today().toordinal() + 30), error_messages = {'invalid': 'A data final deve ser maior que a inicial'})
	dia_evento = forms.DateField(widget=DateTimePicker(options={"format": "DD/MM/YYYY", "pickTime": False}), initial=date.today)
	responsavel = forms.ModelChoiceField(widget=forms.Select(attrs={'class':'form-control'}), queryset=choice)
	intervalo = forms.CharField(widget=forms.Select(attrs={'class':'form-control'}, choices=Evento.INTERVALOS))

	class Meta:
		model = Evento
		fields = ('nome', 'descricao', 'responsavel', 'data_inicio', 'data_fim', 'dia_evento', 'valor_multa',
				'quantidade_intervalos_repeticao', 'intervalo')

	def __init__(self, participantes, *args, **kwargs):
		super(EventoForm, self).__init__(*args, **kwargs)
		self.fields['responsavel'].queryset = participantes
		choice = participantes

	def clean(self):
		cd = self.cleaned_data
		if cd.get('data_fim') < cd.get('data_inicio') or cd.get('data_fim') == cd.get('data_inicio'):
			raise forms.ValidationError(self.fields['data_fim'].error_messages['invalid'])
		elif cd.get('data_inicio') < date.today():
			raise forms.ValidationError(self.fields['data_fim'].error_messages['invalid'])
		if cd.get('intervalo') == 'M':
			data = cd.get('data_fim') - cd.get('data_inicio')
			if int(data.days/30) < 1:
				raise forms.ValidationError(self.fields['data_fim'].error_messages['invalid'])
		return cd


class EditEventoForm(forms.ModelForm):
	choice = None
	nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Informe o nome do evento'}),)
	descricao = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Considerações sobre o evento'}),)
	valor_multa = forms.FloatField(required=True, min_value=0, widget=forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Valor da multa em R$', 'id': 'form_homework', 'step': '0.1'}))
	responsavel = forms.ModelChoiceField(widget=forms.Select(attrs={'class':'form-control'}), queryset=choice)

	class Meta:
		model = Evento
		fields = ('nome', 'descricao', 'responsavel', 'valor_multa')

	def __init__(self, participantes, *args, **kwargs):
		super(EditEventoForm, self).__init__(*args, **kwargs)
		self.fields['responsavel'].queryset = participantes
		choice = participantes

class Comentarios(forms.ModelForm):

	class Meta:
		model = ComentariosDeEventos
		fields = ('texto',)

ambiente/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse, get_list_or_404, Http404
from datetime import date
from .forms import AmbienteForm, EventoForm, EditEventoForm, Comentarios
from .models import Ambiente, User, Evento, ComentariosDeEventos
import PIL
from django.core.paginator import Paginator, InvalidPage, EmptyPage

import json

def novo_ambiente(request):
	if request.method == 'POST':
		form = AmbienteForm(request.POST)
		if form.is_valid():
			ambient = form.save(commit=False)
			ambient.criador = request.user
			ambient.save()
			ambient.participantes.add(request.user)
			return redirect("/")
	else:
		form = AmbienteForm()
	return render(request, 'novo_ambiente.html', {'form':form})

def detalhe_ambiente(request, pk):
	ambiente = get_object_or_404(Ambiente, pk=pk)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	participantes = ambiente.participantes.values()
	tarefas_hj = Evento.objects.filter(ambiente=ambiente).filter(dia_evento=date.today()).order_by('dia_evento')
	tarefas_proximas = Evento.objects.filter(ambiente=ambiente).filter(dia_evento__gt=date.today()).order_by('dia_evento')[0:11]
	resto_tarefas = False
	if len(tarefas_hj) > 2:
		resto_tarefas = len(tarefas_hj) - 2

	multas = Evento.objects.filter(ambiente=ambiente).filter(dia_evento__lt=date.today()).filter(solicitacao_de_validacao=False).order_by('dia_evento')[::-1]
	resto_multas = False
	if len(multas) > 5:
		resto_multas = len(multas) - 5

	return render(request, 'detalhe_ambiente.html', {'ambiente':ambiente,
													'participantes':participantes,
													'tarefas_hj':tarefas_hj[0:2],
													'tarefas_hj_total':tarefas_hj,
													'resto_tarefas':resto_tarefas,
													'tarefas_proximas':tarefas_proximas,
													'multas':multas[0:5],
													'resto_multas':resto_multas})

def participantes(request, pk):
	ambiente = get_object_or_404(Ambiente, pk=pk)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	participantes = ambiente.participantes.get_queryset()
	return render(request, 'participantes.html', {'ambiente':ambiente, 'participantes':participantes})

def remove_user(request):
	if request.method == 'POST' and request.is_ajax():
		try:
			if request.POST.get('iduser') != "" and request.POST.get('house') != "":
				ambient = request.POST.get('house')
				user = request.POST.get('iduser')
				house = get_object_or_404(Ambiente, pk=ambient)
				if house.criador != request.user: raise Http404
				house.participantes.remove(user)
				return HttpResponse(json.dumps(True), content_type="application/json")
			return HttpResponse(json.dumps(False), content_type="application/json")
		except Exception as e:
			print(e)
			return HttpResponse(json.dumps(False), content_type="application/json")
	raise Http404

def deletar_evento(request):
	if request.method == 'POST' and request.is_ajax():
		try:
			if request.POST.get('house') != "" and request.POST.get('idevent') != "":
				ambient = request.POST.get('house')
				event = request.POST.get('idevent')
				house = get_object_or_404(Ambiente, pk=ambient)
				get_object_or_404(house.participantes, pk=request.user.pk)
				if get_list_or_404(Evento, id_agrupador=event)[0].ambiente != house: raise Http404
				Evento.objects.filter(id_agrupador=event).delete()
				#house.participantes.remove(user)
				return HttpResponse(json.dumps(True), content_type="application/json")
			return HttpResponse(json.dumps(False), content_type="application/json")
		except Exception as e:
			print(e)
			return HttpResponse(json.dumps(False), content_type="application/json")
	raise Http404

def add_user(request):
	if request.method == 'POST' and request.is_ajax():
		try:
			if request.POST.get('email') != "" and request.POST.get('house') != "":
				ambient = request.POST.get('house')
				email = request.POST.get('email')
				house = get_object_or_404(Ambiente, pk=ambient)
				if house.criador != request.user: raise Http404
				house.participantes.add(User.objects.get(email=email))
				return HttpResponse(json.dumps(True), content_type="application/json")
			return HttpResponse(json.dumps(False), content_type="application/json")
		except Exception as e:
			print(e)
			return HttpResponse(json.dumps(False), content_type="application/json")
	raise Http404

def eventos(request, pk):
	ambiente = get_object_or_404(Ambiente, pk=pk)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	# participantes = ambiente.participantes.get_queryset()
	return render(request, 'eventos_ambiente.html', {'ambiente':ambiente, 'eventos':ambiente.listar_eventos_agregados()})

def new_evento(request, pk):
	ambiente = get_object_or_404(Ambiente, pk=pk)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	if request.method == 'POST':
		form = EventoForm(ambiente.participantes, request.POST)
		if form.is_valid():
			evento = form.save(commit=False)
			evento.criador = request.user
			evento.ambiente = ambiente
			evento.multipublish()
			return redirect("/ambiente/{}/eventos/{}".format(pk, evento.id_agrupador))
	else:
		form = EventoForm(ambiente.participantes)
	return render(request, 'novo_evento.html', {'form':form, 'ambiente':ambiente})

def evento(request, pk, pkevento):
	ambiente = get_object_or_404(Ambiente, pk=pk)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	evento = get_list_or_404(Evento, id_agrupador=pkevento)
	historico = Evento.objects.filter(id_agrupador=pkevento).filter(dia_evento__lt=date.today())
	paginator = Paginator(historico[::-1], 15) # Mostra 15 contatos por página

    # Make sure page request is an int. If not, deliver first page.
    # Esteja certo de que o `page request` é um inteiro. Se não, mostre a primeira página.
	try:
		page = int(request.GET.get('page', '1'))
	except ValueError:
		page = 1

	# Se o page request (9999) está fora da lista, mostre a última página.
	try:
		lista = paginator.page(page)
	except (EmptyPage, InvalidPage):
		lista = paginator.page(paginator.num_pages)

	return render(request, 'evento.html', {'ambiente':ambiente, 'evento':evento[0], 'historico':lista})

def editar_evento(request, pk, pkevento):
	ambiente = get_object_or_404(Ambiente, pk=pk)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	inst_evento = get_list_or_404(Evento, id_agrupador=pkevento)[0]
	if inst_evento.ambiente != ambiente: raise Http404
	if request.method == 'POST':
		form = EditEventoForm(ambiente.participantes, request.POST, instance=inst_evento)
		if form.is_valid():
			evento = form.save(commit=False)
			# evento.criador = request.user
			# evento.ambiente = ambiente
			Evento.objects.filter(id_agrupador=inst_evento.id_agrupador).update(nome=evento.nome, descricao=evento.descricao, valor_multa=evento.valor_multa, responsavel=evento.responsavel)
			return redirect("/ambiente/{}/eventos/{}".format(pk, evento.id_agrupador))
	else:
		form = EditEventoForm(ambiente.participantes, instance=inst_evento)
	return render(request, 'editar_evento.html', {'form':form, 'ambiente':ambiente, 'evento':inst_evento})

def tarefa(request, pk, pktarefa):
	ambiente = get_object_or_404(Ambiente, pk=pk)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	eventobj = get_object_or_404(Evento, pk=pktarefa)
	comentarios = ComentariosDeEventos.objects.filter(evento=eventobj)
	form = Comentarios(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			com = form.save(commit=False)
			texto = form.cleaned_data['texto']
			com.usuario = request.user
			com.evento = eventobj
			com.save()
			return redirect('/ambiente/'+pk+'/tarefa/'+pktarefa+'/#post')
	return render(request, 'tarefa.html', {'ambiente':ambiente, 'tarefa':eventobj, 'coments':comentarios, 'form':form, 'regras':eventobj.action_rules(), 'multa':eventobj.multa_corrente()})

def solicitacao_validacao(request, pkambiente, pktarefa):
	ambiente = get_object_or_404(Ambiente, pk=pkambiente)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	tarefa = get_object_or_404(Evento, pk=pktarefa)
	if tarefa.responsavel == request.user:
		tarefa.validar_tarefa()
		return redirect('/ambiente/'+pkambiente+'/tarefa/'+pktarefa+'/')
	raise Http404

def refutacao_validacao(request, pkambiente, pktarefa):
	ambiente = get_object_or_404(Ambiente, pk=pkambiente)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	tarefa = get_object_or_404(Evento, pk=pktarefa)
	tarefa.refutar_tarefa()
	return redirect('/ambiente/'+pkambiente+'/tarefa/'+pktarefa+'/')

def proximos_eventos(request, pkambiente):
	ambiente = get_object_or_404(Ambiente, pk=pkambiente)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	tarefas = Evento.objects.filter(ambiente=ambiente).filter(dia_evento__gt=date.today()).order_by('dia_evento')
	paginator = Paginator(tarefas, 14) # Mostra 15 contatos por página

    # Make sure page request is an int. If not, deliver first page.
    # Esteja certo de que o `page request` é um inteiro. Se não, mostre a primeira página.
	try:
		page = int(request.GET.get('page', '1'))
	except ValueError:
		page = 1

	# Se o page request (9999) está fora da lista, mostre a última página.
	try:
		lista = paginator.page(page)
	except (EmptyPage, InvalidPage):
		lista = paginator.page(paginator.num_pages)
	return render(request, 'proximos_eventos.html', {'ambiente':ambiente, 'eventos':lista, 'participantes':User.objects.all()})

def proximos_eventos_por_participante(request, pkambiente, username):
	ambiente = get_object_or_404(Ambiente, pk=pkambiente)
	get_object_or_404(ambiente.participantes, pk=request.user.pk)
	tarefas = Evento.objects.filter(ambiente=ambiente).filter(dia_evento__gt=date.today()).filter(responsavel=get_object_or_404(User, username=username)).order_by('dia_evento')
	paginator = Paginator(tarefas, 14) # Mostra 15 contatos por página

    # Make sure page request is an int. If not, deliver first page.
    # Esteja certo de que o `page request` é um inteiro. Se não, mostre a primeira página.
	try:

ambiente/templates/editar_evento.html
{% extends "base.html" %}
{% load aux_tags %}
{% block titulo %}Alterar {{ evento.nome }} de {{ ambiente.nome }} - Penalty{% endblock titulo %}

{% block conteudo %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3">
		    <nav class="nav-sidebar">
		        <ul class="nav">
		            <li><a href="{% url 'ambiente:ambiente' ambiente.pk %}">Geral</a></li>
		            <li class="nav-divider"></li>
		            <li><a href="{% url 'ambiente:proximos_eventos' ambiente.pk %}">Próximos eventos</a></li>
		            <li><a href="{% url 'ambiente:eventos_passados' ambiente.pk %}">Eventos passados</a></li>
		            <li><a href="{% url 'ambiente:eventos_multados' ambiente.pk %}">Multas</a></li>
		            <li class="nav-divider"></li>
		            <li class="active"><a href="{% url 'ambiente:eventos' ambiente.pk %}">Gerenciar eventos</a></li>
		            <li><a href="{% url 'ambiente:participantes' ambiente.pk %}">Gerenciar participantes</a></li>
		            <li class="nav-divider"></li>
		            <li><a href="javascript:;">Estatísticas</a></li>
		            <li><a href="javascript:;">Sobre o ambiente</a></li>
		        </ul>
		    </nav>
		</div>
	
	<div class="col-sm-9">
		<ol class="breadcrumb">
		  <li><a href="#">Home</a></li>
		  <li><a href="{% url 'ambiente:ambiente' ambiente.pk %}">{{ ambiente.nome }}</a></li>
		  <li><a href="{% url 'ambiente:eventos' ambiente.pk %}">Eventos</a></li>
		  <li><a href="{% url 'ambiente:evento' ambiente.pk evento.id_agrupador %}">{{ evento.nome }}</a></li>
		  <li class="active">Editar evento</li>
		</ol>
		<h3>{{ evento.nome }} - Gerenciar eventos:</h3>
		<hr>
		<div class="panel panel-default">
		  <div class="panel-body">
		  <p>Edite o evento - *Alguns campos não podem ser editados</p>
		  <hr>
		    <form action="{% url 'ambiente:editar_evento' ambiente.pk evento.id_agrupador %}" method="post">
		      {% csrf_token %}
		      {% for field in form %}
		      	<div class="form-group">		      	
    			{{ field.label_tag }} {{ field }}
    			{{ field.errors }}
    			</div>
		      {% endfor %}
			  <button type="submit" class="btn btn-primary btn-block">Salvar alterações</button>
			</form>
		  </div>
		   </div>
		  </div>
	  </div>
	</div>
</div>

{{ form.media }}

	
{% endblock conteudo %}

ambiente/templates/evento.html
{% extends "base.html" %}
{% load aux_tags %}
{% block titulo %}{{ evento.nome }} de {{ ambiente.nome }} - Penalty{% endblock titulo %}

{% block conteudo %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3">
		    <nav class="nav-sidebar">
		    	<ul class="nav">
		            <li><a href="{% url 'ambiente:ambiente' ambiente.pk %}">Geral</a></li>
		            <li class="nav-divider"></li>
		            <li><a href="{% url 'ambiente:proximos_eventos' ambiente.pk %}">Próximos eventos</a></li>
		            <li><a href="{% url 'ambiente:eventos_passados' ambiente.pk %}">Eventos passados</a></li>
		            <li><a href="{% url 'ambiente:eventos_multados' ambiente.pk %}">Multas</a></li>
		            <li class="nav-divider"></li>
		            <li class="active"><a href="{% url 'ambiente:eventos' ambiente.pk %}">Gerenciar eventos</a></li>
		            <li><a href="{% url 'ambiente:participantes' ambiente.pk %}">Gerenciar participantes</a></li>
		            <li class="nav-divider"></li>
		            <li><a href="javascript:;">Estatísticas</a></li>
		            <li><a href="javascript:;">Sobre o ambiente</a></li>
		        </ul>
		    </nav>
		</div>
	
	<div class="col-sm-9">
		<ol class="breadcrumb">
		  <li><a href="#">Home</a></li>
		  <li><a href="{% url 'ambiente:ambiente' ambiente.pk %}">{{ ambiente.nome }}</a></li>
		  <li><a href="{% url 'ambiente:eventos' ambiente.pk %}">Eventos</a></li>
		  <li class="active">{{ evento.nome }}</li>
		</ol>
		<h3>{{ evento.nome }} - Gerenciar eventos:</h3>
		<hr>
		<div class="panel panel-default">
		  {% if evento.intervalo == "D" %}
	  	  	<div class="panel-body dias">
	  	  {% elif evento.intervalo == "S" %}
	  	  	<div class="panel-body semanas">
	  	  {% else %}
	  	    <div class="panel-body meses">
	  	  {% endif %}
		  <p>Detalhes do evento - <a href="{% url 'ambiente:editar_evento' ambiente.pk evento.id_agrupador %}">Editar evento</a> - 
		  	<a href="#" data-toggle="modal" data-target="#modalDeletar">Deletar evento</a></p>
			<div class="modal fade" id="modalDeletar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="exampleModalLabel">Confirmar exclusão de participação de {{ participante.first_name }}</h4>
			      </div>
			      <div class="modal-body">
			      	<p>Ao confirmar esta ação, você excluirá todas as repetições deste evento. Deseja continuar?</p>
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
			        <button type="button" onclick="delete_event({{ ambiente.pk }}, {{ evento.id_agrupador }});" class="btn btn-danger">Excluir {{ evento.nome }} do ambiente</button>
			      </div>
			    </div>
			  </div>
			</div>
		  <hr>
		  	<ul>
		  		<li><b>Descrição do evento:</b> {{ evento.descricao }}</li>
		  		<li><b>Tarefa atribuída para:</b> {{ evento.responsavel.first_name }}</li>
		  		<li><b>Duração do evento:</b> De {{ evento.data_inicio }} até {{ evento.data_fim }}</li>
		  		<li><b>Primeiro dia do evento:</b> {{ evento.dia_evento }} ({{ evento.dia_evento| date:"l" }})</li>
		  		<li><b>Repetição:</b> De {{ evento.quantidade_intervalos_repeticao }} em {{ evento.quantidade_intervalos_repeticao }} {{ evento.intervalo|typedata }}</li>
		  		<li><b>Valor da multa:</b> R$ {{ evento.valor_multa }}</li><br>
		  		<li><b>Criador do evento:</b> {{ evento.criador.first_name }}</li>
		  	</ul>
		  	<br><br>
		  	<h4>Histórico:</h4>
		  	<hr>
		  	{% for evt in historico %}
		  		<a href="{% url 'ambiente:tarefa' ambiente.pk evt.pk %}">{{ evt.dia_evento }} - {{ evt.nome }} (atribuida para {{ evt.responsavel.first_name }})</a><br>
		  	{% empty %}
		  		<p>Ainda não houve nenhuma tarefa para este tipo de evento.</p>
		  	{% endfor %}
		  	<nav aria-label="Page navigation">
			  <ul class="pager">
			    {% if historico.has_previous %}
			    	<li class="previous"><a href="?page={{ historico.previous_page_number }}"><span aria-hidden="true">&larr;</span> Página anterior</a></li>
		        {% endif %}
			    Página {{ historico.number }} de {{ historico.paginator.num_pages }}.
			    {% if historico.has_next %}
			    	<li class="next"><a href="?page={{ historico.next_page_number }}">Próxima página <span aria-hidden="true">&rarr;</span></a></li>
		        {% endif %}
			  </ul>
			</nav>
		  </div>

		   </div>
		  </div>
	  </div>
	</div>
</div>
	
{% endblock conteudo %}

ambiente/templates/novo_ambiente.html
{% extends "base.html" %}
{% block titulo %}Penalty - Novo Ambiente{% endblock titulo %}

{% block conteudo %}


<div class="container">
	<div class="col-lg-10 col-lg-offset-1">
		<div class="card">
		  <div class="card-body">
		<ol class="breadcrumb">
		  <li><a href="/">Home</a></li>
		  <li class="active">Criar ambiente</li>
		</ol>
		   <h4>Crie um ambiente</h4>
		   <hr>
		    <form action="{% url 'ambiente:novo' %}" method="post">
		      {% csrf_token %}
		      {% for field in form %}
		      	<div class="form-group">
		      	{{ field.errors }}
    			{{ field.label_tag }} {{ field }}
    			</div>
		      {% endfor %}
			  <button type="submit" class="btn btn-primary btn-block">Criar</button>
			</form>
		  </div>
		</div>
	</div>		
</div>

{% endblock conteudo %}