ambiente/urls.py
from django.conf.urls import url
from . import views

app_name = "ambiente"

urlpatterns = [
    url(r'^novo/$', views.novo_ambiente, name='novo'),
    url(r'^delete_event/$', views.deletar_evento, name='deletar_evento'),

    url(r'^(?P<pk>[0-9]+)/$', views.detalhe_ambiente, name='ambiente'),

    url(r'^(?P<pkambiente>[0-9]+)/proximos/$', views.proximos_eventos, name='proximos_eventos'),
    url(r'^(?P<pkambiente>[0-9]+)/proximos/(?P<username>[\w.@+-]+)/$', views.proximos_eventos_por_participante, name='proximos_eventos_por_participante'),

    url(r'^(?P<pkambiente>[0-9]+)/passados/$', views.eventos_passados, name='eventos_passados'),
    url(r'^(?P<pkambiente>[0-9]+)/passados/(?P<username>[\w.@+-]+)/$', views.eventos_passados_por_participante, name='eventos_passados_por_participante'),

    url(r'^(?P<pkambiente>[0-9]+)/multas/$', views.eventos_multados, name='eventos_multados'),
    # url(r'^(?P<pkambiente>[0-9]+)/passados/(?P<username>[\w.@+-]+)/$', views.eventos_passados_por_participante, name='eventos_passados_por_participante'),

    url(r'^(?P<pk>[0-9]+)/participantes/$', views.participantes, name='participantes'),
    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^remove_user/$', views.remove_user, name='remove_user'),

    url(r'^(?P<pk>[0-9]+)/eventos/$', views.eventos, name='eventos'),
    url(r'^(?P<pk>[0-9]+)/eventos/novo/$', views.new_evento, name='novoevento'),
    url(r'^(?P<pk>[0-9]+)/eventos/editar/(?P<pkevento>[0-9]+)$', views.editar_evento, name='editar_evento'),
    url(r'^(?P<pk>[0-9]+)/eventos/(?P<pkevento>[0-9]+)/$', views.evento, name='evento'),

    url(r'^(?P<pk>[0-9]+)/tarefa/(?P<pktarefa>[0-9]+)/$', views.tarefa, name='tarefa'),
    url(r'^(?P<pkambiente>[0-9]+)/tarefa/(?P<pktarefa>[0-9]+)/validar$', views.solicitacao_validacao, name='solicitacao_validacao'),
    url(r'^(?P<pkambiente>[0-9]+)/tarefa/(?P<pktarefa>[0-9]+)/refutar$', views.refutacao_validacao, name='refutacao_validacao'),
]

core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_page, name='login'),
	url(r'^autentica/$', views.entrar),
	url(r'^registra/$', views.register),
	url(r'^logout/$', views.make_logout),
	url(r'^minhaconta/$', views.settings, name='settings'),
	url(r'^excluiUser/$', views.excluiUser),
]

penalty/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles import views
import django

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ambiente/', include('ambiente.urls')),
    url(r'^', include('core.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

# Create your models here.

core/views.py
from django.shortcuts import render, HttpResponse, Http404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from .models import User
from ambiente.models import Ambiente
import json

@login_required(login_url='/login')
def index(request):	
	meus_ambientes = Ambiente.objects.filter(participantes=request.user)
	return render(request, 'index.html', {'meus_ambientes': meus_ambientes})

def login_page(request):
	if request.user.is_authenticated(): return index(request)
	return render(request, 'login.html')

def entrar(request):
	if request.method == 'POST' and request.is_ajax():
		user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponse(json.dumps(True), content_type="application/json")
		return HttpResponse(json.dumps(False), content_type="application/json")
	raise Http404

def register(request):
	if request.method == 'POST' and request.is_ajax():
		userInstance = User()
		userInstance.first_name = request.POST.get('name')
		userInstance.username = request.POST.get('username')
		userInstance.email = request.POST.get('email')
		passw = request.POST.get('password')
		userInstance.set_password(passw)
		userInstance.save()
		print("user: "+ userInstance.username)
		print("senha: "+ passw)
		user = authenticate(username=userInstance.username, password=passw)
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponse(json.dumps(True), content_type="application/json")
		return HttpResponse(json.dumps(False), content_type="application/json")
	raise Http404

def make_logout(request):	
	logout(request)
	return redirect("/")

def settings(request):
	if not request.user.is_authenticated():
		raise Http404
	else:
		#detalhes = get_object_or_404(Profile, user=request.user)
		#form = UserFormRegister(request.POST or None, instance=request.user)
		if request.POST:
			print('entrou na funçao')

			name = request.POST.get('first_name')
			#lastname = request.POST.get('last_name')
			#username = request.POST.get('username')
			email = request.POST.get('email')
			password = request.POST.get('password')
			repassword = request.POST.get('repassword')
			oldpassword = request.POST.get('oldpassword')
			print(name)
			#print(lastname)
			print(password)
			print(email)
			print(repassword)
			print(oldpassword)

			if name == '' or email == '' or password == '' or repassword == '' or oldpassword == '':
				return render(request, 'settings.html', {'error_name':'* Este campo é obrigatório.'})

			if request.user.check_password(oldpassword) == False:
				print('senha incorreta')
				return render(request, 'settings.html', {'error_de_senha': 'Senha atual está incorreta'})

			if password != repassword:
				return render(request, 'settings.html', {'error_de_reg': 'Senhas não conferem'})

			request.user.first_name = name
			request.user.email = email
			request.user.set_password(password)
			request.user.save()
			user = authenticate(username=request.user.username, password=password)
			login(request, user)
			#email_alteracao.delay(request.user.first_name, request.user.last_name, request.user.username, request.user.email)
			return render(request, 'settings.html', {'success':'Alteração feita com sucesso!'})
		return render(request, 'settings.html')

def excluiUser(request):
	if not request.user.is_authenticated():
		raise Http404
	else:
		if request.method == 'POST':
			idvi = request.POST.get('id')
			resultado = False
			if request.user.check_password(idvi) == True:
				request.user.delete()
				resultado = True
			return HttpResponse(json.dumps(resultado), content_type="application/json")
		return HttpResponse(json.dumps(False), content_type="application/json")

core/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
     <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <title>{% block titulo %}{% endblock titulo %}</title>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Penalty</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/">Início</a></li>
          <li><a href="#">Sobre</a></li>
          <li><a href="#">Meus dados</a></li>
          <li><a href="#">Meu histórico</a></li>
        </ul>
        {% if request.user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.first_name }} <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'core:settings' %}">Minha conta</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/logout/">Sair</a></li>
            </ul>
          </li>
        </ul>
        {% endif %}
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
    </nav>
    {% block conteudo %}
      
    {% endblock conteudo %}

  </body>
</html>

core/templates/index.html
{% extends "base.html" %}

{% block titulo %}Penalty - Página Inicial{% endblock titulo %}

{% block conteudo %}

<div class="container">
	<h3>Olá, {{ request.user.first_name }}!</h3>
	<hr>
	<div class="col-sm-4">
  	  <div class="panel panel-default">
  	  	<div class="panel-body">
  	  		<h4>Suas tarefas hoje:</h4>
  	  		<hr>
  	  		<h4>Próximas tarefas</h4>
  	  		<hr>
	    </div>
	  </div>
    </div>
    <div class="col-sm-4">
  	  <div class="panel panel-default">
  	  	<div class="panel-body">
  	  		<h4>Retrospecto:</h4>
  	  		<hr>
	    </div>
	  </div>
    </div>
    <div class="col-sm-4">
  	  <div class="panel panel-default">
  	  	<div class="panel-body">
  	  		<h4>Ambientes:</h4>
  	  		<hr>
  	  		{% for amb in meus_ambientes %}
  			<div class="panel panel-default">
  				<div class="panel-body">
  					<p class="pCinzaUser">
				    	<a href="{% url 'ambiente:ambiente' amb.pk %}" class="titulopindex">{{ amb.nome }}</a><span class="pCinza"></span>
					</p>
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				    	<small class="pCinzaUser">
				    		Criado em {{ amb.data_criacao }}
				    	</small>
				    </div>
  				</div>
  			</div>
  	  		{% empty %}
  	  			
  	  		{% endfor %}
	    </div>
	  </div>
    </div>

</div>


	
{% endblock conteudo %}

core/templates/login.html
{% extends "base.html" %}

{% block titulo %}Penalty - Gerenciador de tarefas domiciliares{% endblock titulo %}

{% block conteudo %}
<div class="container">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-default">
		  <div class="panel-body">
		    Faça login no formulário abaixo.
		   <hr>
		    <form id='logar' method="post"> {% csrf_token %}
			  <div class="form-group">
			    <label for="exampleInputEmail1">Username:</label>
			    <input type="text" class="form-control" id="aunome" placeholder="Insira seu username">
			    <span class="help-block desaparece">Insira um nome de usuário válido.</span>
			  </div>
			  <div class="form-group">
			    <label for="exampleInputPassword1">Senha:</label>
			    <input type="password" class="form-control" id="ausenha" placeholder="Insira sua senha">
			    <span class="help-block desaparece">Insira uma senha válida.</span>
			  </div>
			  <button type="submit" id="btnlogin" class="btn btn-primary btn-block">Entrar</button>

			</form>
			<br>
			Não tem cadastro? Faça <a href="#" data-toggle="modal" data-target="#modalRegistro">aqui</a>!
		  </div>
		</div>
  </div>
</div>

<div class="modal fade" id="modalRegistro" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Registro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Faça seu cadastro na plataforma abaixo.
			  <hr>
		    <form id="register">
		    	<div class="form-group">Nome:</label>
				    <input type="text" class="form-control" id="nomer" placeholder="Insira seu nome" required>
				  </div>
				  <div class="form-group">
				    <label for="exampleInputEmail1">Username:</label>
				    <input type="text" class="form-control" id="userr" placeholder="Insira seu username" required>
				  </div>
				  <div class="form-group">
				    <label for="exampleInputEmail1">Email:</label>
				    <input type="text" class="form-control" id="emailr" placeholder="Insira seu email">
				  </div>
				  <hr>
				  <div class="form-group">
				    <label for="exampleInputPassword1">Senha:</label>
				    <input type="password" class="form-control" id="passwordr" placeholder="Insira sua senha">
				  </div>
				  <div class="form-group">
				    <label for="exampleInputPassword1">Repita a senha:</label>
				    <input type="password" class="form-control" id="repasswordr" placeholder="Insira sua novamente sua senha">
				  </div>
				  <button type="submit" id="btnregister" class="btn btn-primary btn-block">Registrar-se!</button>
				</form>
      </div>
    </div>
  </div>
</div>
{% endblock conteudo %}

core/templates/settings.html
{% extends "base.html" %}

{% block titulo %}Penalty - Gerenciador de tarefas domiciliares{% endblock titulo %}

{% block conteudo %}
<div class="container">
		<div class="row">
			<h3>Configurações da conta</h3>
			<hr>
			<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
				<div class="panel panel-default">
				  <div class="panel-body">
				  	Altere sua conta
				  	<hr>
					<form action="{% url 'core:settings' %}" class="form-horizontal" method="post">
						{% if success %}
							<div class="modal fade" id="modalSuccess" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
							  <div class="modal-dialog" role="document">
							    <div class="modal-content">
							      <div class="modal-header">
							        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							        <h4 class="modal-title" id="exampleModalLabel">Sucesso!</h4>
							      </div>
							      <div class="modal-body">
							      	<p>Sua conta foi alterada com sucesso!</p>
							      	<p>Encaminhamos um email para {{ request.user.email }} confirmando as alterações.</p>
							      </div>
							    </div>
							  </div>
							</div>
							<script type="text/javascript">
								$('#modalSuccess').modal('show');
							</script>
						{% endif %}
						
						{% csrf_token %}
						<div class="form-group">
							<label for="first_name" class="col-xs-4 control-label">
								Nome:
							</label>
							<div class="col-xs-8">
								<input type="text" class="form-control" id="nomeRegistro"  name="first_name" placeholder="{{ error_name }}" value="{{ request.user.first_name }}">
							</div>
						</div>

						<div class="form-group">
							<label for="username" class="col-xs-4 control-label">
								Username:
							</label>
							<div class="col-xs-8">
								<input type="text" class="form-control" id="nomeRegistro"  name="username" value="{{ request.user.username }}" disabled>
							</div>
						</div>

						<div class="form-group">
							<label for="email" class="col-xs-4 control-label">
								Endereço de email:
							</label>
							<div class="col-xs-8">
								<input type="text" class="form-control" id="nomeRegistro"  name="email" placeholder="{{ error_name }}" value="{{ request.user.email }}">
							</div>
						</div>

						<div class="form-group">
							<label for="password" class="col-xs-4 control-label">
								Nova senha:
							</label>
							{% if error_name %}
								<div class="col-xs-8">
									<input type="password" class="form-control" id="nomeRegistro"  name="password" placeholder="{{ error_name }}">
								</div>
							{% else %}
								<div class="col-xs-8">
								<input type="password" class="form-control" id="nomeRegistro"  name="password" placeholder="{{ error_de_reg }}">
							</div>
							{% endif %}							
						</div>

						<div class="form-group">
							<label for="repassword" class="col-xs-4 control-label">
								Repita a nova senha:
							</label>
							{% if error_name %}
								<div class="col-xs-8">
									<input type="password" class="form-control" id="nomeRegistro"  name="repassword" placeholder="{{ error_name }}">
								</div>
							{% else %}
								<div class="col-xs-8">
								<input type="password" class="form-control" id="nomeRegistro"  name="repassword" placeholder="{{ error_de_reg }}">
							</div>
							{% endif %}			
						</div>

						<div class="form-group has-warning">
							<label for="oldpassword" class="col-xs-4 control-label">
								Senha atual:
							</label>
							{% if error_name %}
								<div class="col-xs-8">
									<input type="password" class="form-control" id="nomeRegistro"  name="oldpassword" placeholder="{{ error_name }}">
								</div>
							{% else %}
								<div class="col-xs-8">
								<input type="password" class="form-control" id="nomeRegistro"  name="oldpassword" placeholder="{{ error_de_senha }}">
							</div>
							{% endif %}			
						</div>
						<div class="col-xs-4 col-xs-offset-8 col-sm-4 col-sm-offset-8 col-md-4 col-md-offset-8 col-lg-4 col-lg-offset-8">
							
							<button type="submit" class="btn btn-success" id="entrar">Salvar alterações</button>
						</div>						
					</form>
					<div class="col-xs-7 col-xs-offset-5 col-sm-7 col-sm-offset-5 col-md-7 col-md-offset-5 col-lg-7 col-lg-offset-5">
						<button class="btn btn-danger btn-link" data-toggle="modal" data-target="#exampleModal">Excluir conta</button>
					</div>
				</div>
			</div>
		</div>

		<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="exampleModalLabel">Deletar conta</h4>
		      </div>
		      <div class="modal-body">
		      	<p>Para excluir sua conta é preciso informar sua senha:</p>
		          <div class="form-group">
		            <label for="recipient-name" class="control-label">Senha:</label>
		            <input type="password" class="form-control" id="recipientsenha">
		          </div>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
		        <button type="button" class="btn btn-primary" onclick="excluiConta()">Excluir conta</button>
		      </div>
		    </div>
		  </div>
		</div>

		<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
			<div class="panel panel-default">
			  <div class="panel-body">
			  	Recomendações:
			  	<hr>
			    <ul class="list-group">
				  <li class="list-group-item">Você não pode alterar o <b>Username</b>.</li>
				  <li class="list-group-item">Deve-se informar a senha atual para salvar as alterações</li>
				  <li class="list-group-item">Para maior segurança, forneça uma senha contendo pelo menos letras e numeros num total maior que 8 caracteres. </li>
				  <li class="list-group-item">Tenha cautela caso for alterar a senha, certifique-se de memoriza-lá antes de realizar as devidas mudanças. </li>
				  <li class="list-group-item">Todos os campos são <b>obrigatórios</b>. </li>
				</ul>
			  </div>
			</div>
			
		</div>
		</div>
	</div>
{% endblock conteudo %}